# Project: ifToDarTo
# Makefile created by Embarcadero Dev-C++ 6.3

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../sekeh/main.o
LINKOBJ  = ../sekeh/main.o
LIBS     = -L"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/lib" -L"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/include" -I"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include"
CXXINCS  = -I"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/include" -I"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/x86_64-w64-mingw32/include" -I"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include" -I"S:/devCPlusPlus/Dev-Cpp/TDM-GCC-64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/c++"
BIN      = ifToDarTo.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = S:\devCPlusPlus\Dev-Cpp\DevCpp.exe INTERNAL_DEL

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

../sekeh/main.o: ../sekeh/main.cpp
	$(CPP) -c ../sekeh/main.cpp -o ../sekeh/main.o $(CXXFLAGS)
